Use MyFinalDB_ByungSuJung;
go

insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZip) values ('Greenholt and Sons', '704-528-0866', '782 Veith Place', 'Charlotte', 'NC', '28284');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZip) values ('Rutherford LLC', '814-117-4795', '8 Lawn Crossing', 'Erie', 'PA', '16522');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZip) values ('Heathcote, Morar and Ankunding', '803-974-1978', '1 Warner Circle', 'Columbia', 'SC', '29225');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZip) values ('Legros-Rowe', '330-768-4473', '6 Magdeline Park', 'Akron', 'OH', '44321');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZip) values ('Barton-Streich', '312-327-2361', '04 Leroy Road', 'Chicago', 'IL', '60630');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZip) values ('Barton-Ratke', '646-840-9297', '578 Milwaukee Plaza', 'New York City', 'NY', '10060');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZip) values ('Kunde, Anderson and Barrows', '941-398-0334', '970 Washington Hill', 'Sarasota', 'FL', '34233');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZip) values ('Schroeder Group', '936-380-9273', '0 Morning Crossing', 'Huntsville', 'TX', '77343');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZip) values ('O''Hara, Brekke and MacGyver', '863-721-8856', '15 Del Sol Crossing', 'Lakeland', 'FL', '33805');
insert into Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress, ClinicCity, ClinicState, ClinicZip) values ('Zieme-Green', '757-730-6987', '6800 Warrior Trail', 'Norfolk', 'VA', '23520');

Select * From vClinics;
Go

insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Gusta', 'Menego', '813-675-1613', '1 Bluestem Crossing', 'Zephyrhills', 'FL', '33543');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Deina', 'Shovell', '515-105-7250', '47 Walton Street', 'Des Moines', 'IA', '50981');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Fredelia', 'Baumaier', '469-891-3780', '9 Gale Junction', 'Plano', 'TX', '75074');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Martino', 'Aitchinson', '716-530-7807', '0601 Melody Pass', 'Buffalo', 'NY', '14220');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Kathleen', 'Whaymand', '313-236-0456', '682 Buena Vista Alley', 'Detroit', 'MI', '48275');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Erie', 'Sinnocke', '360-980-1782', '4 Bunting Lane', 'Seattle', 'WA', '98158');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Annora', 'Budd', '915-681-8752', '3 Manitowish Center', 'El Paso', 'TX', '88519');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Felicity', 'Eyden', '786-228-5394', '074 Pawling Hill', 'Miami', 'FL', '33190');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Hardy', 'Heal', '816-437-1281', '9433 Schiller Pass', 'Kansas City', 'MO', '64153');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Kippy', 'Whitaker', '217-345-5252', '21 Daystar Park', 'Springfield', 'IL', '62756');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Kassey', 'Shervington', '843-653-1494', '5 Atwood Junction', 'Charleston', 'SC', '29411');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Sol', 'Smeeth', '254-646-7600', '2 Iowa Parkway', 'Waco', 'TX', '76711');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Shirlee', 'Ifill', '202-109-6553', '557 Pepper Wood Drive', 'Washington', 'DC', '20430');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Lindsey', 'Yurenin', '704-570-9441', '86326 Steensland Terrace', 'Charlotte', 'NC', '28215');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Adelice', 'Sanders', '478-103-6035', '071 Pennsylvania Street', 'Macon', 'GA', '31296');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Cristabel', 'April', '818-963-5958', '212 Pierstorff Hill', 'Los Angeles', 'CA', '90035');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Connie', 'Cuncarr', '256-292-9257', '51 Karstens Terrace', 'Huntsville', 'AL', '35815');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Xylia', 'Terris', '386-487-9881', '5 Vidon Pass', 'Daytona Beach', 'FL', '32128');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Anthia', 'Loblie', '907-280-1548', '255 Union Plaza', 'Anchorage', 'AK', '99599');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Ginger', 'Janjusevic', '706-897-2633', '37 Del Mar Crossing', 'Athens', 'GA', '30610');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Kayley', 'Kiff', '325-993-3227', '01665 Lillian Trail', 'Abilene', 'TX', '79605');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Kevin', 'Keddie', '515-344-7759', '62866 Starling Way', 'Des Moines', 'IA', '50981');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Darrick', 'Klossmann', '941-528-7952', '2494 Ruskin Drive', 'Sarasota', 'FL', '34233');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Gretchen', 'Naldrett', '434-581-5799', '36940 Comanche Place', 'Lynchburg', 'VA', '24515');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Vincent', 'Balogh', '210-965-0361', '1 Lakeland Circle', 'San Antonio', 'TX', '78285');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Philippa', 'Paulsen', '404-792-2300', '943 Independence Lane', 'Alpharetta', 'GA', '30022');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Stoddard', 'Eakins', '714-228-7048', '9 Larry Hill', 'San Jose', 'CA', '95128');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Dennison', 'Rowthorne', '913-596-7218', '93268 Florence Avenue', 'Shawnee Mission', 'KS', '66220');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Dian', 'Gosnold', '517-508-5284', '66149 Troy Street', 'Lansing', 'MI', '48956');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Siobhan', 'Anniwell', '952-439-8935', '5485 Michigan Park', 'Young America', 'MN', '55564');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Neddy', 'Kaindl', '217-853-1939', '8 2nd Circle', 'Springfield', 'IL', '62764');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Tommy', 'Winward', '615-450-5518', '31 Washington Hill', 'Nashville', 'TN', '37205');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Camellia', 'Gamlin', '615-121-6245', '59296 Swallow Hill', 'Nashville', 'TN', '37235');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Nerti', 'Falvey', '918-994-0081', '362 Kropf Plaza', 'Tulsa', 'OK', '74141');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Anatole', 'Kyneton', '412-688-8319', '4623 Blackbird Place', 'Pittsburgh', 'PA', '15255');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Garrard', 'Lunnon', '404-275-9892', '929 Carpenter Alley', 'Atlanta', 'GA', '31132');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Ethelred', 'Elijah', '229-260-1946', '930 Talisman Drive', 'Valdosta', 'GA', '31605');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Manolo', 'Galler', '205-812-7575', '139 Old Gate Drive', 'Tuscaloosa', 'AL', '35487');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Haily', 'Franses', '313-348-2396', '50659 Glendale Pass', 'Detroit', 'MI', '48267');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Sibley', 'Isaksson', '619-919-5444', '9134 Maple Circle', 'San Diego', 'CA', '92196');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Charley', 'Highton', '651-965-5657', '80267 Fallview Crossing', 'Minneapolis', 'MN', '55407');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Kalil', 'Headley', '317-456-6336', '3750 Armistice Lane', 'Indianapolis', 'IN', '46247');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Aindrea', 'Tinner', '303-943-4866', '0 Bellgrove Avenue', 'Denver', 'CO', '80262');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Padraig', 'Acey', '212-618-3392', '75 Ridgeway Alley', 'New York City', 'NY', '10045');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Manda', 'Birtley', '763-613-5031', '99 Bluestem Center', 'Monticello', 'MN', '55590');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Domenico', 'Coppard', '918-221-6941', '7297 Sundown Crossing', 'Tulsa', 'OK', '74149');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Pammie', 'Hallstone', '704-800-9034', '033 American Ash Plaza', 'Charlotte', 'NC', '28215');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Jacinthe', 'McAlindon', '847-166-2162', '26 Glendale Parkway', 'Evanston', 'IL', '60208');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Cosette', 'Blaksland', '480-155-5547', '41 Kings Terrace', 'Phoenix', 'AZ', '85040');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Atalanta', 'Dunbabin', '504-406-8364', '70504 Truax Court', 'New Orleans', 'LA', '70183');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Tonye', 'Aguirrezabal', '405-494-2843', '091 Meadow Valley Park', 'Oklahoma City', 'OK', '73119');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Sybilla', 'Kyme', '520-833-9979', '0 Rockefeller Avenue', 'Tucson', 'AZ', '85732');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Ravid', 'de Clercq', '817-323-7927', '13278 Morning Junction', 'Fort Worth', 'TX', '76105');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Rora', 'Royden', '608-495-6214', '9 School Street', 'Madison', 'WI', '53716');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Farand', 'McCromley', '757-955-4033', '0960 Schurz Junction', 'Virginia Beach', 'VA', '23471');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Cammi', 'Wycliffe', '336-868-5709', '230 Marcy Avenue', 'Greensboro', 'NC', '27404');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Tracey', 'Greest', '786-490-1889', '7607 Independence Circle', 'Miami', 'FL', '33111');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Cookie', 'Wretham', '682-860-9513', '7 Nobel Crossing', 'Fort Worth', 'TX', '76178');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Becki', 'Dohmann', '216-477-2968', '57029 Debs Center', 'Cleveland', 'OH', '44118');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Gregoor', 'Goldster', '801-977-9891', '2 Prentice Center', 'Provo', 'UT', '84605');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Quintilla', 'Shaw', '317-383-2660', '7 Graedel Parkway', 'Indianapolis', 'IN', '46254');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Dorette', 'Queste', '228-218-0318', '555 Delladonna Park', 'Gulfport', 'MS', '39505');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Keary', 'Dauby', '217-882-6701', '93466 Sullivan Plaza', 'Springfield', 'IL', '62756');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Edgardo', 'Bossingham', '501-432-9727', '3368 Walton Trail', 'Hot Springs National Park', 'AR', '71914');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Romola', 'De Bernardi', '651-523-5111', '06 Rockefeller Center', 'Minneapolis', 'MN', '55441');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Kurt', 'Dove', '217-627-1070', '8513 Donald Point', 'Springfield', 'IL', '62794');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Debora', 'Silcox', '225-351-7504', '4 Shoshone Alley', 'Baton Rouge', 'LA', '70826');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Hilda', 'Everix', '678-806-4557', '955 Daystar Court', 'Marietta', 'GA', '30066');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Barret', 'Rapps', '202-205-3912', '136 Stoughton Street', 'Washington', 'DC', '20205');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Correy', 'Fransewich', '917-864-9989', '436 Utah Court', 'New York City', 'NY', '10034');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Vonny', 'Pinkerton', '937-646-9305', '66364 Brentwood Road', 'Dayton', 'OH', '45414');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Roxy', 'Romain', '231-941-3056', '72743 Mesta Lane', 'Muskegon', 'MI', '49444');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Korie', 'Joynes', '281-275-8415', '8590 Stephen Terrace', 'Pasadena', 'TX', '77505');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Thaddeus', 'Vivians', '214-500-5900', '96 Springview Pass', 'Dallas', 'TX', '75392');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Walliw', 'Gedney', '704-150-7063', '73 Dakota Junction', 'Charlotte', 'NC', '28205');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Kesley', 'Pendle', '417-150-5047', '4149 Fuller Hill', 'Springfield', 'MO', '65805');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Tiffie', 'Opie', '412-239-7380', '25 3rd Park', 'Pittsburgh', 'PA', '15225');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Worthington', 'Apark', '614-341-7618', '41005 Loftsgordon Trail', 'Columbus', 'OH', '43231');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Benjie', 'Philipart', '770-517-0423', '102 Manitowish Court', 'Marietta', 'GA', '30066');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Barnett', 'Lipmann', '858-174-5123', '2 Brentwood Junction', 'San Diego', 'CA', '92121');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Hamish', 'Puvia', '816-140-8942', '52 Sunfield Lane', 'Kansas City', 'MO', '64179');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Eudora', 'Jackman', '919-112-0385', '47683 Paget Junction', 'Raleigh', 'NC', '27690');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Arlena', 'Girdlestone', '910-807-3846', '580 Forest Run Alley', 'Fayetteville', 'NC', '28314');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Wat', 'Mulligan', '434-972-9036', '717 Quincy Avenue', 'Manassas', 'VA', '22111');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Berny', 'Barents', '678-430-5070', '300 Waxwing Crossing', 'Atlanta', 'GA', '30328');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Julie', 'Hunton', '614-758-9174', '6756 Talmadge Road', 'Columbus', 'OH', '43204');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Fina', 'Damerell', '918-296-2541', '557 Becker Pass', 'Tulsa', 'OK', '74141');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Hymie', 'Helversen', '561-852-9138', '930 Arapahoe Court', 'Lake Worth', 'FL', '33462');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Lorain', 'Dameisele', '225-601-7567', '5790 Spenser Avenue', 'Baton Rouge', 'LA', '70810');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Arlana', 'Klementz', '916-131-9471', '21919 Merry Pass', 'Sacramento', 'CA', '95828');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Tamara', 'McCaighey', '205-387-5418', '796 Scofield Road', 'Birmingham', 'AL', '35242');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Regine', 'Levine', '212-886-9488', '50957 Granby Avenue', 'Brooklyn', 'NY', '11254');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Hatty', 'Rizzello', '312-653-2591', '38 Crowley Way', 'Chicago', 'IL', '60652');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Gilemette', 'Cartmael', '260-508-3564', '546 Acker Road', 'Fort Wayne', 'IN', '46896');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Jess', 'Lowres', '203-355-9575', '6083 Monument Hill', 'New Haven', 'CT', '06533');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Marketa', 'Bullar', '202-819-2649', '67 Glendale Road', 'Alexandria', 'VA', '22309');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Aigneis', 'McCrory', '602-555-2910', '8 Thompson Center', 'Phoenix', 'AZ', '85035');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Heddi', 'Flanders', '754-142-5227', '56 Bellgrove Lane', 'Fort Lauderdale', 'FL', '33310');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Scarlet', 'Brickdale', '845-208-3231', '268 Dorton Way', 'White Plains', 'NY', '10606');
insert into Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress, PatientCity, PatientState, PatientZip) values ('Baxy', 'Aleksashin', '302-206-2470', '705 Hooker Place', 'Wilmington', 'DE', '19810');

Select * From vPatients;
Go

insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZip) values ('Borg', 'Matton', '858-234-5758', '3 Superior Lane', 'San Diego', 'CA', '92121');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZip) values ('Ricky', 'Ronald', '561-332-1734', '7400 Knutson Place', 'Boynton Beach', 'FL', '33436');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZip) values ('Perle', 'Keeling', '806-489-8895', '94 Anthes Crossing', 'Amarillo', 'TX', '79118');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZip) values ('Ethelin', 'Vaggers', '559-105-2177', '37369 Upham Street', 'Fullerton', 'CA', '92640');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZip) values ('Ibby', 'Crookall', '915-657-4875', '26 Maywood Court', 'El Paso', 'TX', '88569');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZip) values ('Devin', 'Pawden', '651-528-5594', '39703 Paget Junction', 'Saint Paul', 'MN', '55103');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZip) values ('Terrance', 'Lealle', '616-496-2231', '475 2nd Street', 'Grand Rapids', 'MI', '49518');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZip) values ('Vaclav', 'Ackwood', '904-234-8240', '61 Butternut Hill', 'Jacksonville', 'FL', '32225');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZip) values ('Kacie', 'Wegenen', '830-129-3071', '469 Clarendon Hill', 'San Antonio', 'TX', '78245');
insert into Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress, DoctorCity, DoctorState, DoctorZip) values ('Dorey', 'Bienvenu', '951-509-4040', '58172 Blue Bill Park Pass', 'Corona', 'CA', '92878');

Select * From Doctors;
Go

insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-12-27', '10:50:21', 65, 9, 4);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-05-10', '0:17:34', 86, 2, 8);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-07-28', '2:42:52', 84, 5, 3);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-04-02', '17:36:54', 63, 11, 4);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-08-25', '5:09:10', 67, 2, 11);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-02-16', '15:52:34', 99, 7, 7);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-10-25', '2:26:26', 9, 2, 3);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-09-11', '5:08:20', 3, 3, 5);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-01-10', '19:56:20', 101, 6, 3);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-04-04', '23:20:34', 35, 5, 7);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-12-05', '11:28:20', 57, 6, 8);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-08-12', '16:56:15', 70, 5, 5);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-10-20', '1:34:45', 46, 2, 8);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-01-12', '3:44:07', 33, 4, 5);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-03-04', '4:08:54', 88, 5, 6);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-06-26', '5:37:20', 75, 5, 2);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-07-06', '16:36:47', 100, 10, 6);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-11-26', '17:26:31', 47, 7, 9);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-12-27', '14:49:41', 101, 4, 2);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-02-04', '9:58:07', 44, 5, 3);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-10-27', '7:54:17', 66, 9, 11);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-04-21', '0:48:17', 14, 11, 2);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-03-28', '22:02:38', 79, 2, 2);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-07-27', '13:26:58', 98, 8, 9);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-09-14', '3:04:30', 3, 2, 7);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-06-11', '19:30:18', 62, 5, 6);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-02-17', '19:25:43', 60, 7, 8);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-05-08', '16:33:15', 84, 11, 6);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-07-16', '2:27:10', 4, 10, 4);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-06-18', '17:35:53', 49, 10, 7);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-08-10', '7:44:01', 60, 10, 9);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-08-05', '1:11:50', 11, 6, 10);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-02-06', '0:13:33', 31, 2, 10);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-09-07', '22:11:00', 83, 10, 4);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-10-12', '23:30:58', 47, 11, 9);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-11-22', '7:29:23', 81, 3, 11);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-12-24', '14:52:03', 38, 7, 9);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-06-10', '8:51:24', 16, 8, 4);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-05-25', '2:31:34', 89, 2, 6);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-12-22', '15:42:18', 47, 4, 8);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-07-30', '12:55:18', 50, 10, 11);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-08-21', '12:19:07', 97, 2, 10);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-04-20', '16:30:15', 9, 4, 6);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-03-17', '15:32:48', 79, 9, 6);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-04-28', '14:15:23', 69, 7, 11);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-09-07', '15:45:27', 47, 7, 4);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-07-08', '2:25:19', 89, 6, 3);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-04-29', '21:02:09', 15, 3, 9);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-07-20', '23:46:40', 37, 8, 7);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-05-30', '11:52:45', 37, 6, 9);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-08-10', '19:47:41', 7, 6, 3);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-04-09', '0:27:15', 20, 10, 11);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-08-23', '21:46:36', 71, 3, 6);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-07-05', '6:54:31', 65, 8, 8);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-11-28', '3:20:35', 5, 7, 2);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-05-22', '9:32:23', 84, 4, 7);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-08-02', '21:38:06', 46, 10, 10);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-06-13', '10:08:46', 5, 4, 8);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-01-31', '13:40:17', 22, 9, 7);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-10-26', '19:31:37', 6, 2, 8);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-02-19', '17:46:57', 78, 7, 2);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-05-11', '8:06:27', 12, 2, 9);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-01-24', '1:10:05', 22, 7, 9);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-01-27', '2:02:35', 90, 2, 3);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-11-17', '8:29:09', 69, 7, 5);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-07-06', '3:11:36', 84, 5, 9);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-09-26', '17:22:12', 54, 9, 4);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-06-29', '12:48:48', 30, 6, 10);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-04-06', '23:16:34', 91, 2, 2);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-02-16', '20:38:27', 55, 5, 4);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-03-11', '22:15:48', 22, 8, 3);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-08-30', '10:27:16', 54, 11, 5);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-03-04', '4:59:11', 36, 4, 2);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-10-16', '16:39:30', 24, 9, 7);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-09-03', '9:43:58', 87, 8, 9);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-12-15', '4:50:40', 38, 2, 7);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-12-20', '12:41:24', 21, 3, 11);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-04-12', '18:09:35', 50, 6, 6);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-02-13', '1:22:00', 47, 11, 11);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-05-12', '20:33:59', 68, 3, 10);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-12-28', '10:09:04', 80, 6, 4);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-09-04', '11:05:23', 68, 9, 3);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-09-28', '4:51:01', 47, 11, 6);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-04-23', '3:10:54', 66, 5, 10);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-07-03', '8:27:16', 57, 2, 11);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-10-03', '10:09:14', 6, 6, 7);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-06-05', '10:43:57', 16, 9, 3);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-03-19', '19:41:52', 47, 11, 6);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-10-11', '0:20:59', 98, 8, 9);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-07-01', '15:51:09', 65, 8, 5);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-03-19', '16:21:11', 31, 8, 4);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-05-26', '2:44:57', 29, 4, 7);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-08-28', '4:48:02', 26, 10, 9);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-11-21', '16:01:47', 64, 3, 10);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-09-03', '0:46:36', 14, 8, 6);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-06-28', '1:58:45', 58, 6, 8);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-01-10', '13:00:10', 19, 8, 9);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-10-12', '5:59:02', 81, 8, 3);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2019-02-24', '1:11:29', 80, 8, 11);
insert into Appointments (AppointmentDate, AppointmentTime, AppointmentPatientID, AppointmentDoctorID, AppointmentClinicID) values ('2018-10-10', '1:34:00', 84, 5, 6);

Select * From vAppointments;
Go